// agent/agent.js

require("dotenv").config();
const OpenAI = require("openai");

const {
  getGlobalMarketData,
  getIndianMarketData,
} = require("./Tools/marketTool");

const { getMarketNews } = require("./Tools/newsTool");
const { sendEmail } = require("./Tools/emailTool");

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// Tool registry
// Maps the tool name generated by the LLM
// to the actual JavaScript function.
const toolRegistry = {
  getGlobalMarketData,
  getIndianMarketData,
  getMarketNews,
  sendEmail,
};

// Tool definitions
// These are sent to the LLM so it knows which tools are available,
// what they do, and what arguments they accept.
const tools = [
  {
    type: "function",
    function: {
      name: "getGlobalMarketData",
      description: "Fetch the latest global market data.",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "getIndianMarketData",
      description: "Fetch the latest Indian market data.",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "getMarketNews",
      description: "Fetch the latest market-related news.",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "sendEmail",
      description: "Send the generated market report by email.",
      parameters: {
        type: "object",
        properties: {
          report: {
            type: "string",
            description: "The market report to send by email.",
          },
        },
        required: ["report"],
        additionalProperties: false,
      },
    },
  },
];

// System prompt
const systemPrompt = `
You are an autonomous financial analysis agent.

You MUST ONLY use these tools:
- getGlobalMarketData
- getIndianMarketData
- getMarketNews
- sendEmail

Workflow:
1. Fetch global market data.
2. Fetch Indian market data.
3. Fetch market news if needed.
4. Analyze the available data.
5. Generate a concise report.
6. Always send the report using sendEmail, whether the analysis succeeds or partially fails.

Rules:
- Do not invent tool names.
- If any tool fails, continue with the available data.
- Keep the report concise.
- Always attempt to send the email.
`;

// Main agent
async function runAgent() {
  let messages = [
    {
      role: "system",
      content: systemPrompt,
    },
    {
      role: "user",
      content: "Generate today's market report",
    },
  ];

  let maxSteps = 6;

  while (maxSteps-- > 0) {
    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      messages,
      tools,
    });

    const msg = response.choices[0].message;

    // Always add the assistant message before adding tool results.
    messages.push(msg);

    // No tool call means the model has produced its final response.
    if (!msg.tool_calls || msg.tool_calls.length === 0) {
      console.log("Final Output:\n", msg.content);
      break;
    }

    // Execute all tool calls returned by the model.
    for (const toolCall of msg.tool_calls) {
      const functionName = toolCall.function.name;

      let args = {};

      try {
        args = JSON.parse(toolCall.function.arguments || "{}");
      } catch (err) {
        console.error(
          `Invalid arguments for tool ${functionName}:`,
          err.message
        );

        messages.push({
          role: "tool",
          tool_call_id: toolCall.id,
          content: JSON.stringify({
            error: "Invalid JSON arguments",
          }),
        });

        continue;
      }

      console.log("Calling tool:", functionName);
      console.log("Arguments:", args);

      const tool = toolRegistry[functionName];

      // Safety check
      if (!tool) {
        console.error("Invalid tool:", functionName);

        messages.push({
          role: "tool",
          tool_call_id: toolCall.id,
          content: JSON.stringify({
            error: `Tool ${functionName} not found`,
          }),
        });

        continue;
      }

      try {
        const result = await tool(args);

        console.log("Tool result:", result);

        messages.push({
          role: "tool",
          tool_call_id: toolCall.id,
          content: JSON.stringify(result),
        });
      } catch (err) {
        console.error(
          `Tool execution failed for ${functionName}:`,
          err.message
        );

        messages.push({
          role: "tool",
          tool_call_id: toolCall.id,
          content: JSON.stringify({
            error: err.message,
          }),
        });
      }
    }
  }

  if (maxSteps <= 0) {
    console.log("Agent stopped because MAX_STEPS was reached.");
  }
}

module.exports = { runAgent };
